# Generated by Django 5.0.4 on 2024-06-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='num',
            field=models.CharField(default='asd110', max_length=10),
        ),
    ]
