# Generated by Django 5.0.4 on 2024-06-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_appointment_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('experience', models.CharField(max_length=10)),
                ('doctor_id', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default='123', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
