# Generated by Django 5.0.4 on 2024-06-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_add_doctor_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='add_doctor',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
    ]
