# Generated by Django 5.0.4 on 2024-06-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0006_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bill',
            field=models.BigIntegerField(default='1499'),
        ),
    ]
