# Generated by Django 5.0.4 on 2024-06-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0007_patient_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bill',
            field=models.BigIntegerField(default=1499),
        ),
    ]
